apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: irsa-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/baasilmirza/aws-eks-platform.git
    path: argocd/irsa-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: irsa-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
